### PR TITLE
Update blueprint.json

### PR DESCRIPTION
**Pull request by ghost**
@dolph Hi Dolph, can we update the demo to a production URL, the staging one seems perpetually broke.

### CODE REVIEW

**Comment by ghost** [comment]
@stevemart

**Comment by stevemar** [comment]
@nching1969 is https://discovery-github.mybluemix.net/ running this code base? it looks a bit different than the screenshot in the README: https://github.com/IBM/watson-discovery-analyze-data-breaches/blob/master/doc/source/images/sample-output.png

**Comment by ghost** [comment]
@stevemart No, it is changed from the original application.  That said, so is the current demoURL value.  Dolph updated it for me awhile ago.  While the starter kit was only in staging, this disconnect seemed ok.    

This is the original application running : https://discovery-orig.mybluemix.net/ if you want to change it to this for now, or remove it altogether.  

We need to meet with you and Watson dev ex to decide whether to update the Journey  
https://developer.ibm.com/code/journey/import-enrich-and-gain-insight-from-data/.  It is actually pretty generic although the youtube video would show the old application.  This github repo would need a few updates.

**Comment by stevemar** [comment]
@nching1969 i totally agree that having something that doesn't point to staging is a good thing :)

I guess we need to decide if we're going with https://discovery-github.mybluemix.net or https://discovery-orig.mybluemix.net/ -- do you have the git repo for the "new" one?

**Review by stevemar — APPROVED** [review]
i'm going to merge this since it's better than pointing to staging.

**Pull request merged**
